### ISSUE TITLE
Capability relocations not generated for .L.str cap table entries.

### ISSUE THREAD

**Issue by qwattash** [CTSRD-CHERI/lld#19]
LLD skips .L.str.xxx symbols when populating the cap table.
This seems to happen to avoid duplicate symbol errors when creating symbols for each cap table entry, because .L.str.xxx symbols are not globally numbered.

I believe that we may avoid generating the cap table symbol related to .L.str symbols and just emit the capability relocation for the cap table entry.
Alternatively we can uniquifiy the cap table symbol names to avoid duplicates.

I implemented the latter hotfix in qwattash/lld@56ca6ce28acfbfc544aab41f1b45618c8fc5cea6

**Comment by arichardson** [comment]
Ah seems like I broke this in https://github.com/CTSRD-CHERI/lld/commit/ef511486ce574a0032bbf9bd41d5c8be6c93d01f since the add is now after the continue.

The fix you added looks good to me. Originally that loop only added the symbol names so continuing was fine. But now that I also add the cap relocs it should never skip an interation.

 The `if (Name.empty())` also seems problematic since it can result in a skipped cap reloc. I'll see if I can come up with a testcase for that.
